version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  app:
    build: ./app
    container_name: app
    networks:
      - default
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - EXCHANGE_NAME=fibo
    restart: on-failure
    depends_on:
      - rabbitmq
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build: ./worker
    container_name: worker
    networks:
      - default
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - EXCHANGE_NAME=fibo
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure
    command: ["./worker/wait-for-it.sh", "rabbitmq:5672", "--", "python", "./worker/main.py"]

networks:
  default: {}